import Head from "next/head";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from '../styles/Home.module.css'
import Link from "next/link";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>Hello World <br/>Welcome to Next.js</h1>

        <p className={styles.text}>Get started by editing <code>pages/index.js</code></p>
        <p className={styles.text}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam ducimus harum sequi at exercitationem provident quisquam nihil, officia obcaecati ullam? Totam suscipit quis, porro dicta saepe ad repellendus natus dolore?</p>

        <Link href="/more">
          <a className={styles.btn}>Learn More</a>
        </Link>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
